[tool.poetry]
name = "pjecz-plataforma-web-cli"
version = "1.0.0"
description = "Interfaz de Linea de Comando hecho en Typer/Python para consultar Plataforma Web API OAuth2"
authors = ["Guillermo Valdes <guillermo.valdes@pjecz.gob.mx>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
typer = "^0.6.1"
rich = "^12.5.1"
Unidecode = "^1.3.4"
python-dotenv = "^0.20.0"
tabulate = "^0.8.10"
pandas = "^1.4.3"
sendgrid = "^6.9.7"
dominate = "^2.7.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
pylint = "^2.14.5"
black = "^22.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 256
