[tool.poetry]
name = "pjecz-plataforma-web-cli"
version = "1.1.0"
description = "Interfaz de Linea de Comando hecho en Typer/Python para consultar Plataforma Web"
authors = ["Guillermo Valdes <guillermo.valdes@pjecz.gob.mx>"]
license = "AGPL3"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.2"
typer = "^0.7.0"
rich = "^13.3.3"
Unidecode = "^1.3.6"
python-dotenv = "^1.0.0"
tabulate = "^0.9.0"
pandas = "^2.0.0"
sendgrid = "^6.10.0"
dominate = "^2.7.0"

[tool.poetry.dev-dependencies]
pylint = "^2.17.2"
black = "^23.3.0"
pytest = "^7.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 256
